# Generated by Django 4.2.7 on 2024-02-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voyage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"verbose_name": "Content", "verbose_name_plural": "Content"},
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together={("program", "course", "content")},
        ),
    ]
